Update README.md to mark repo as archived
alphagov/passport-verify pull request #128
Opened 2023-08-10 14:12 UTC by EduardoAquinta

As agreed in [verify-architecture ADR 0039](https://github.com/alphagov/verify-architecture/blob/master/adr/0039-use-prs-before-archiving-repos.md), a PR must be approved by all engineers on the team before being archived.

Approving this PR indicates approval for this repo to be archived.

2023-08-10 14:12 UTC, PaulHennessey approved these changes, later dismissed

2023-08-10 14:37 UTC, owenblacker commented on README.md
>  [![Greenkeeper badge](https://badges.greenkeeper.io/alphagov/passport-verify.svg)](https://greenkeeper.io/)
Remove all 3 of the icon things

2023-08-10 14:38 UTC, owenblacker requested changes
Remove the icon things from lines 3–5 please. (Sorry, I should have said.)

2023-08-10 15:02 UTC, EduardoAquinta commented on README.md
>  [![Greenkeeper badge](https://badges.greenkeeper.io/alphagov/passport-verify.svg)](https://greenkeeper.io/)
I have deleted lines 3-5 :)

2023-08-11 10:52 UTC, owenblacker approved these changes
LGTM

2023-08-11 10:53 UTC, merged